# Generated by Django 2.1.7 on 2019-06-02 02:39

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guess_word', models.CharField(max_length=100)),
                ('taboo_words', models.CharField(max_length=100)),
                ('data', django.contrib.postgres.fields.jsonb.JSONField(editable=False, null=True)),
            ],
        ),
    ]